version: 2
jobs:
  build:
    environment:
      TZ: "/usr/share/zoneinfo/Europe/London"
    docker:
      - image: circleci/node:6.11.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Packages
          command: npm install
      - store_artifacts:
          path: test/nightwatch/screenshots/
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # Run tests
      - run:
          name: Run Tests
          command: touch .env
